/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as HowlsRouteRouteImport } from './routes/howls/route'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as HowlsIndexRouteImport } from './routes/howls/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as HowlsHowlIdRouteImport } from './routes/howls/$howlId'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const HowlsRouteRoute = HowlsRouteRouteImport.update({
  id: '/howls',
  path: '/howls',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRouteRoute,
} as any)
const HowlsIndexRoute = HowlsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HowlsRouteRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRouteRoute,
} as any)
const HowlsHowlIdRoute = HowlsHowlIdRouteImport.update({
  id: '/$howlId',
  path: '/$howlId',
  getParentRoute: () => HowlsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/howls': typeof HowlsRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/howls/$howlId': typeof HowlsHowlIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/howls/': typeof HowlsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/redirect': typeof RedirectRoute
  '/howls/$howlId': typeof HowlsHowlIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/howls': typeof HowlsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/howls': typeof HowlsRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/howls/$howlId': typeof HowlsHowlIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/howls/': typeof HowlsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/howls'
    | '/users'
    | '/redirect'
    | '/howls/$howlId'
    | '/users/$userId'
    | '/howls/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to: '/redirect' | '/howls/$howlId' | '/users/$userId' | '/howls' | '/users'
  id:
    | '__root__'
    | '/howls'
    | '/users'
    | '/redirect'
    | '/howls/$howlId'
    | '/users/$userId'
    | '/howls/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HowlsRouteRoute: typeof HowlsRouteRouteWithChildren
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
  RedirectRoute: typeof RedirectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/howls': {
      id: '/howls'
      path: '/howls'
      fullPath: '/howls'
      preLoaderRoute: typeof HowlsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/howls/': {
      id: '/howls/'
      path: '/'
      fullPath: '/howls/'
      preLoaderRoute: typeof HowlsIndexRouteImport
      parentRoute: typeof HowlsRouteRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/howls/$howlId': {
      id: '/howls/$howlId'
      path: '/$howlId'
      fullPath: '/howls/$howlId'
      preLoaderRoute: typeof HowlsHowlIdRouteImport
      parentRoute: typeof HowlsRouteRoute
    }
  }
}

interface HowlsRouteRouteChildren {
  HowlsHowlIdRoute: typeof HowlsHowlIdRoute
  HowlsIndexRoute: typeof HowlsIndexRoute
}

const HowlsRouteRouteChildren: HowlsRouteRouteChildren = {
  HowlsHowlIdRoute: HowlsHowlIdRoute,
  HowlsIndexRoute: HowlsIndexRoute,
}

const HowlsRouteRouteWithChildren = HowlsRouteRoute._addFileChildren(
  HowlsRouteRouteChildren,
)

interface UsersRouteRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HowlsRouteRoute: HowlsRouteRouteWithChildren,
  UsersRouteRoute: UsersRouteRouteWithChildren,
  RedirectRoute: RedirectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
